# Generated by Django 5.0.6 on 2024-06-15 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asignatura_state_asignatura_user_detallenota_nota1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='descripcion',
            new_name='periodo',
        ),
    ]
