# Generated by Django 5.0.6 on 2024-06-15 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asignatura_created_asignatura_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallenota',
            name='valor',
        ),
    ]
