# Generated by Django 5.0.6 on 2024-06-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_detallenota_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallenota',
            name='recuperacion',
            field=models.FloatField(default=0.0),
        ),
    ]
